name: Terraform CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:

jobs:
  CD_terraform:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 60
    environment: ${{ github.event.inputs.environment }}
    permissions:
      # workload identity連携によるToken発行には以下権限が必要
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Configure AWS credentials (AssumeRole)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::392329150290:role/terraform-assume-role
        aws-region: ap-northeast-1
        role-duration-seconds: 3600

    - name: Verify AWS authentication
      run: |
        echo "Checking AWS credentials..."
        aws sts get-caller-identity

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Terraform init
      working-directory: ./env/${{ github.event.inputs.environment }}
      run: terraform init

    - name: Terraform plan
      working-directory: ./env/${{ github.event.inputs.environment }}
      run: terraform plan
  
    - name: Terraform Apply
      working-directory: ./env/${{ github.event.inputs.environment }}
      run: terraform apply -auto-approve