name: Terraform CI

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  CI_terraform:
    runs-on: [self-hosted, Linux, X64]
    #env: 
      #TF_PLUGIN_CACHE_DIR: $HOME/.terraform.d/plugin-cache
    strategy:
      matrix:
        environment: [dev] # 現状1環境のみ 
    timeout-minutes: 60
    permissions:
      # workload identity連携によるToken発行には以下権限が必要
      id-token: write
      contents: read

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Configure AWS Credentials (AssumeRole)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::392329150290:role/terraform-assume-role
        aws-region: ap-northeast-1
        role-duration-seconds: 3600

    - name: Verify AWS Authentication
      run: |
        echo "Checking AWS credentials..."
        aws sts get-caller-identity

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.52.0

   # - name: Config Terraform Plugin Cache
   #   run: mkdir -p $TF_PLUGIN_CACHE_DIR

    - name: Check HOME
      run: |
        echo "HOME=$HOME"
        ls -la $HOME

    - name: Cache Terraform Plugins
      uses: actions/cache@v3
      with:
        path: /home/ec2-user/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
            ${{ runner.os }}-terraform-

    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Init TFLint
      run: tflint --init
      continue-on-error: true

    - name: Run TFLint
      run: tflint --recursive
      continue-on-error: true

    - name: Terraform Init All Dir
     # env: 
       # TF_PLUGIN_CACHE_DIR: $HOME/.terraform.d/plugin-cache
      run: |
        pwd
        cd /home/ec2-user
        pwd
        ls -la
        export TF_PLUGIN_CACHE_DIR="/home/ec2-user/.terraform.d/plugin-cache"
        mkdir -p "$TF_PLUGIN_CACHE_DIR"
        cd /home/ec2-user/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws
        ls -la
        find . -name "*.tf" -exec dirname {} \; | sort -u | xargs -I {} sh -c 'cd "{}" && terraform init'
      continue-on-error: true
        #export TF_PLUGIN_CACHE_DIR="/home/ec2-user/.terraform.d/plugin-cache"
        #mkdir -p "$TF_PLUGIN_CACHE_DIR"
        #find . -name "*.tf" -exec dirname {} \; | sort -u | xargs -I {} sh -c 'cd "{}" && terraform init'
    - name: Terraform Validation
      run: find . -name "*.tf" -exec dirname {} \; | sort -u | xargs -I {} sh -c 'cd "{}" && terraform validate'
      continue-on-error: true

    - name: Confilm
      run: |
        ls -la

    - name: Select Terraform Workspace
      working-directory: env/${{ matrix.environment }}
      run: |
        if terraform workspace list | grep -qw "${{ matrix.environment }}"; then
          echo "Workspace ${{ matrix.environment }} exists. Selecting it."
          terraform workspace select "${{ matrix.environment }}"
        else
          echo "Workspace ${{ matrix.environment }} does not exist. Creating it."
          terraform workspace new "${{ matrix.environment }}"
        fi

    - name: Terraform Plan
      working-directory: env/${{ matrix.environment }}
      run: terraform plan
