name: Terraform CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

job:
  terraform_CI:
    runs-on:

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials (AssumeRole)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::392329150290:role/terraform-assume-role
        aws-region: ap-northeast-1
        role-duration-seconds: 3600
        role-chsnging: true

    - name: Verify AWS authentication
      run: |
        echo "Checking AWS credentials..."
        aws sts get-caller-identity

    - name: Terraform install
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version:1.5.7

    - name: Terraform init
      working-directory: env
      run: terraform init

    - name: Terraform format check
      run: terraform fmt -check

    - name: Terraform validate
      run: terraform validate

    - name: Terraform plan
      if: github.event_name === 'pull_request'
      working-directory: env
      run: terraform plan